# Generated by Django 5.0.4 on 2024-04-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_one_off_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='one_off_payment',
            new_name='total_amount',
        ),
    ]
