# Generated by Django 5.0.4 on 2024-04-28 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
    ]
