# Generated by Django 5.0.4 on 2024-04-28 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_payment_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.consumer'),
        ),
    ]
